# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 082777c820b4bd384ebc44767650286f7b948b694a66811dca92bda2217b84fdf9cb534e68df50104346aaab95d7bbec75edef9c1f1960aad37ffe28ec9b17ee

test:
  secret_key_base: cdfe0903a6d5f37905059ebe8223294d3f2276142645d9300ea1d82b8b68b17ad0638e0a99f3556ec241fd3455039f8862836c02d13484805e4d2aefe214c7b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
